### ISSUE TITLE
Mobile, Mobile, Mobile \o/ 

### ISSUE THREAD

**Issue by naaando** [elementary-br/website#10]
Responsive plz

**Comment by ghost** [comment]
https://github.com/mctoddynho/elementary-br.github.io
meu fork, está responsivo 👍. Ou pode mudar nos meus path pull's requests hehe

**Comment by naaando** [comment]
@mctoddynho Não brinca kkk

**Comment by ghost** [comment]
kkkkkk

**Comment by naaando** [comment]
LOL, foi um comentário interno mas o bot que usamos publicou

**Comment by leonardo-lemos** [comment]
@mctoddynho Você pode abrir um PR, please?

**Comment by ghost** [comment]
![screenshot_2](https://user-images.githubusercontent.com/31263378/37404168-75d3ce42-2767-11e8-8d20-3e4dd0d27fe5.png)
@leonardo-lemos sou meio leigo aqui no github, mas acho que fiz sim... 
(caso não seja, desculpe mesmo, sou muito burro asfaksdjfasdfakdjfkadjfk)

**Comment by ghost** [comment]
https://github.com/elementary-br/elementary-br.github.io/compare/master...mctoddynho:patch-1?expand=1

https://github.com/elementary-br/elementary-br.github.io/compare/master...mctoddynho:patch-2?expand=1

acho q foi como comentarios... LOL

**Comment by leonardo-lemos** [comment]
@mctoddynho Mesclei todas as suas mudanças, muito obrigado! Quaisquer mudanças futuras serão bem vindas! :)
