### ISSUE TITLE
Implementação de backend simples

### ISSUE THREAD

**Issue by leonardo-lemos** [elementary-br/website#16]
Precisamos de um backend que implemente, inicialmente, uma classe/função que traga os últimos x posts do Medium da comunidade e popule a seção de últimos posts do site.

- O backend deve ser desenvolvido em PHP
- Deve ser simples, porém modular, para que seja possível expandi-lo futuramente
- Se possível deve fazer cache dos últimos posts
- Deve obter os posts através da API do Medium

**Comment by PabloDinella** [comment]
Pessoal, como comentei no PR #19:

O que precisamos basicamente é fazer um get em https://medium.com/elementarybr/latest?format=json e disponibilizar esse json em um endpoint que nosso site possa usar. 

Nosso VPS na Digital Ocean vai ser principalmente para o Discourse, poderíamos rodar o código que faz o descrito acima lá, porém tenho uma sugestão:

Já qua vamos fazer um site estático (a única coisa dinâmica vai ser o feed do medium), sugiro usarmos  a hospedagem gratuita do Firebase para hospedar o site, e criar uma Cloud Function no Firebase também, que faz o que está descrito acima. Ambas as hospedagem e cloud functions tem cotas bem generosas no plano gratuito, inclusivo domínio grátis com SSL já incluso: https://firebase.google.com/pricing/

O que acham?

**Comment by leonardo-lemos** [comment]
Avaliei os requisitos sugeridos pelos @PabloDinella e vi que seria melhor implementar desta maneira, +1 em migrar para o Firebase e disponibilizar um API para obter o feed.

**Comment by PabloDinella** [comment]
Não deu pra usar o firebase pois o plano free não deixa fazer requisições para redes fora da google (eu não havia entendido isso na tabela de preços do firebase). Então acabei criando uma aplicação simples em node e fiz o deploy no now.sh, onde o plano grátis parece ser suficiente pra gente.

Repositório criado: https://github.com/elementary-br/medium-posts-api-gateway
