### ISSUE TITLE
Alinhar logo verticalmente no menu

### ISSUE THREAD

**Issue by leonardo-lemos** [elementary-br/website#4]
@PabloDinella disse que isso pode ser feito com flex-box.

**Comment by naaando** [comment]
Resolvido aqui
- https://github.com/elementary-br/elementary-br.github.io/commit/d2a79fac402ed87674e48cbab420ec62ba2890cb
- https://github.com/elementary-br/elementary-br.github.io/commit/2f05f267f5cd4929b08853295da8bc94211b8334
